tasks:
  - init: |
      cargo build
    command: |
      cargo run
  - init: |
      sh -c "$(curl -sSfL https://release.solana.com/v1.9.5/install)"
    command: |
      solana-install update
      solana --version



vscode:
  extensions:
    - matklad.rust-analyzer